// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// blosc-feats.cpp
list blosc_info_(raws data);
extern "C" SEXP _blosc_blosc_info_(SEXP data) {
  BEGIN_CPP11
    return cpp11::as_sexp(blosc_info_(cpp11::as_cpp<cpp11::decay_t<raws>>(data)));
  END_CPP11
}
// compress.cpp
raws blosc_compress_dat(raws data, std::string compressor, int level, int doshuffle, int typesize);
extern "C" SEXP _blosc_blosc_compress_dat(SEXP data, SEXP compressor, SEXP level, SEXP doshuffle, SEXP typesize) {
  BEGIN_CPP11
    return cpp11::as_sexp(blosc_compress_dat(cpp11::as_cpp<cpp11::decay_t<raws>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(compressor), cpp11::as_cpp<cpp11::decay_t<int>>(level), cpp11::as_cpp<cpp11::decay_t<int>>(doshuffle), cpp11::as_cpp<cpp11::decay_t<int>>(typesize)));
  END_CPP11
}
// compress.cpp
raws blosc_decompress_dat(raws data);
extern "C" SEXP _blosc_blosc_decompress_dat(SEXP data) {
  BEGIN_CPP11
    return cpp11::as_sexp(blosc_decompress_dat(cpp11::as_cpp<cpp11::decay_t<raws>>(data)));
  END_CPP11
}
// dtype.cpp
strings check_dt_units();
extern "C" SEXP _blosc_check_dt_units() {
  BEGIN_CPP11
    return cpp11::as_sexp(check_dt_units());
  END_CPP11
}
// dtype.cpp
list dtype_to_list_(std::string dtype);
extern "C" SEXP _blosc_dtype_to_list_(SEXP dtype) {
  BEGIN_CPP11
    return cpp11::as_sexp(dtype_to_list_(cpp11::as_cpp<cpp11::decay_t<std::string>>(dtype)));
  END_CPP11
}
// dtype.cpp
sexp dtype_to_r_(raws data, std::string dtype, sexp na_value);
extern "C" SEXP _blosc_dtype_to_r_(SEXP data, SEXP dtype, SEXP na_value) {
  BEGIN_CPP11
    return cpp11::as_sexp(dtype_to_r_(cpp11::as_cpp<cpp11::decay_t<raws>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(dtype), cpp11::as_cpp<cpp11::decay_t<sexp>>(na_value)));
  END_CPP11
}
// dtype.cpp
raws r_to_dtype_(sexp data, std::string dtype, sexp na_value);
extern "C" SEXP _blosc_r_to_dtype_(SEXP data, SEXP dtype, SEXP na_value) {
  BEGIN_CPP11
    return cpp11::as_sexp(r_to_dtype_(cpp11::as_cpp<cpp11::decay_t<sexp>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(dtype), cpp11::as_cpp<cpp11::decay_t<sexp>>(na_value)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_blosc_blosc_compress_dat",   (DL_FUNC) &_blosc_blosc_compress_dat,   5},
    {"_blosc_blosc_decompress_dat", (DL_FUNC) &_blosc_blosc_decompress_dat, 1},
    {"_blosc_blosc_info_",          (DL_FUNC) &_blosc_blosc_info_,          1},
    {"_blosc_check_dt_units",       (DL_FUNC) &_blosc_check_dt_units,       0},
    {"_blosc_dtype_to_list_",       (DL_FUNC) &_blosc_dtype_to_list_,       1},
    {"_blosc_dtype_to_r_",          (DL_FUNC) &_blosc_dtype_to_r_,          3},
    {"_blosc_r_to_dtype_",          (DL_FUNC) &_blosc_r_to_dtype_,          3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_blosc(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
