# Generated by cpp11: do not edit by hand

blosc_compress_dat <- function(data, compressor, level, doshuffle, typesize) {
  .Call(`_blosc_blosc_compress_dat`, data, compressor, level, doshuffle, typesize)
}

blosc_decompress_dat <- function(data) {
  .Call(`_blosc_blosc_decompress_dat`, data)
}

dtype_to_list_ <- function(dtype) {
  .Call(`_blosc_dtype_to_list_`, dtype)
}

dtype_to_r_ <- function(data, dtype, na_value) {
  .Call(`_blosc_dtype_to_r_`, data, dtype, na_value)
}

r_to_dtype_ <- function(data, dtype, na_value) {
  .Call(`_blosc_r_to_dtype_`, data, dtype, na_value)
}
