# Generated by cpp11: do not edit by hand

blosc_version <- function() {
  .Call(`_blosc_blosc_version`)
}

nthreads <- function() {
  .Call(`_blosc_nthreads`)
}

blosc_compress_dat <- function(data, compressor, level, doshuffle, typesize) {
  .Call(`_blosc_blosc_compress_dat`, data, compressor, level, doshuffle, typesize)
}

blosc_compress_con <- function(con, compressor, level, doshuffle, typesize) {
  .Call(`_blosc_blosc_compress_con`, con, compressor, level, doshuffle, typesize)
}

blosc_decompress <- function(data) {
  .Call(`_blosc_blosc_decompress`, data)
}

dtype_to_r <- function(data, dtype, na_value) {
  .Call(`_blosc_dtype_to_r`, data, dtype, na_value)
}
