# Generated by cpp11: do not edit by hand

blosc_version <- function() {
  .Call(`_blosc_blosc_version`)
}

blosc_test <- function() {
  invisible(.Call(`_blosc_blosc_test`))
}

nthreads <- function() {
  .Call(`_blosc_nthreads`)
}

blosc_compress <- function(data, level, doshuffle, typesize) {
  .Call(`_blosc_blosc_compress`, data, level, doshuffle, typesize)
}

blosc_decompress <- function(data) {
  .Call(`_blosc_blosc_decompress`, data)
}

dtype_to_r <- function(data, dtype, na_value) {
  .Call(`_blosc_dtype_to_r`, data, dtype, na_value)
}
